#!/usr/bin/env ruby

require 'json'
require "b2flow/manager/executor"

# config = {
#     "name": "x-dag",
#     "config": {},
#     "team": "x-team",
#     "project": "x-project",
#     "jobs": [
#         {
#             "name": "job_name",
#             "depends": [],
#             "full_name": "x-team_x-project_x-dag_job_name",
#             "version": 1577984308,
#             "engine": {
#                 "cpu": 2,
#                 "memory": 4096,
#                 "type": "DockerEngine"
#             },
#             "image": "gcr.io/eco-league-244218/x-team_x-project_x-dag_job_name:1577984308"
#         }
#     ]
# }
#
# ENV.update({"B2FLOW__DAG__CONFIG" => config.to_json})

B2flow::Manager::Executor.new.run